
# Use Node.js as the base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the remaining files
COPY . .

# Specify the port the application will listen on
EXPOSE 4000

# Command to run the application
CMD ["npm", "start"]
